version: '3.5'

services:
  example-backend:
    build:
      context: example-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=172.16.0.4
    command: ./server
    networks:
      default:
        ipv4_address: 172.16.0.2

  example-frontend:
    build:
      context: example-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: /usr/bin/serve -s -l 5000 build
    networks:
      default:
        ipv4_address: 172.16.0.3

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      default:
        ipv4_address: 172.16.0.4

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.0.0/24

