version: '3.5'

services:
  example-backend:
    build:
      context: example-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: ./server
    depends_on:
      - example-frontend

  example-frontend:
    build:
      context: example-frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: /usr/bin/serve -s -l 5000 build

